# Generated by Django 4.2.1 on 2023-06-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='list_id',
            new_name='todo_list',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='user_id',
            new_name='user',
        ),
    ]
